// produccion/src/components/os-data-table.jsx
import { useState, useMemo, useEffect, useRef, useCallback } from "react"
import { createPortal } from "react-dom"
import {
  SlidersHorizontal, Download, X, Filter, ChevronUp, ChevronDown,
  FileText, Table as TableIcon, FileIcon, Inbox,
} from "lucide-react"
import { cn } from "@/lib/utils"

const AGG_OPTIONS = [
  { value: 'sum', label: 'Suma',     icon: 'Σ' },
  { value: 'avg', label: 'Promedio', icon: 'x̄' },
  { value: 'max', label: 'Máximo',   icon: '↑' },
  { value: 'min', label: 'Mínimo',   icon: '↓' },
]

const OP_LABELS = {
  eq: 'Igual a', contains: 'Contiene',
  gt: 'Mayor que', lt: 'Menor que',
  gte: 'Mayor o igual', lte: 'Menor o igual',
  between: 'Entre',
}

export function OsDataTable({
  rows = [],
  columns = [],
  loading = false,
  title = '',
  onRowClick,
  renderCell,  // función: (row, col, value) => ReactNode | null (null = usar default)
}) {
  const [localColumns, setLocalColumns] = useState([])
  useEffect(() => { setLocalColumns(columns.map(c => ({ ...c }))) }, [columns])

  const visibleColumns = useMemo(() => localColumns.filter(c => c.visible !== false), [localColumns])

  // Toolbar popups
  const [showFields, setShowFields] = useState(false)
  const [showExport, setShowExport] = useState(false)
  const toolbarRef = useRef(null)

  useEffect(() => {
    const handler = (e) => {
      if (!toolbarRef.current?.contains(e.target)) {
        setShowFields(false)
        setShowExport(false)
      }
    }
    document.addEventListener('click', handler)
    return () => document.removeEventListener('click', handler)
  }, [])

  // Column popup
  const [colPopup, setColPopup] = useState(null)
  const [colPopupStyle, setColPopupStyle] = useState({})
  const inputRef = useRef(null)

  const openColPopup = (key, event) => {
    if (colPopup === key) { setColPopup(null); return }
    const rect = event.currentTarget.getBoundingClientRect()
    setColPopupStyle({ top: (rect.bottom + 4) + 'px', left: Math.max(4, rect.left) + 'px' })
    setColPopup(key)
    setTimeout(() => inputRef.current?.focus(), 50)
  }

  // Column filters
  const [columnFilters, setColumnFilters] = useState({})
  const getFilterOp = (k) => columnFilters[k]?.op || 'eq'
  const getFilterVal = (k) => columnFilters[k]?.val || ''
  const getFilterVal2 = (k) => columnFilters[k]?.val2 || ''

  const setFilter = (k, patch) => {
    setColumnFilters(prev => ({
      ...prev,
      [k]: { op: 'eq', val: '', val2: '', selected: [], ...prev[k], ...patch },
    }))
  }

  const getColumnOptions = (k) => {
    const col = localColumns.find(c => c.key === k)
    if (!col?.options) return []
    return col.options.map(o => typeof o === 'string' ? { value: o, label: o } : o)
  }

  const isOptionSelected = (k, v) => (columnFilters[k]?.selected || []).includes(v)
  const toggleOption = (k, v) => {
    const selected = [...(columnFilters[k]?.selected || [])]
    const idx = selected.indexOf(v)
    if (idx === -1) selected.push(v); else selected.splice(idx, 1)
    setFilter(k, { selected })
  }

  const hasFilter = (k) => {
    const f = columnFilters[k]
    if (!f) return false
    if ((f.selected || []).length > 0) return true
    return (f.val || '').trim() !== ''
  }

  const activeFilterCount = useMemo(
    () => Object.keys(columnFilters).filter(k => hasFilter(k)).length,
    [columnFilters]
  )

  const clearAllFilters = () => setColumnFilters({})

  // Sort
  const [sortKey, setSortKey] = useState('')
  const [sortDir, setSortDir] = useState('asc')
  const setSort = (k, dir) => {
    if (sortKey === k && sortDir === dir) setSortKey('')
    else { setSortKey(k); setSortDir(dir) }
  }

  // Aggregates
  const [columnAggregates, setColumnAggregates] = useState({})
  const toggleAggregate = (k, type) => {
    setColumnAggregates(prev => {
      if (prev[k] === type) { const c = { ...prev }; delete c[k]; return c }
      return { ...prev, [k]: type }
    })
  }
  const activeAggregateCount = Object.keys(columnAggregates).length
  const hasAggregates = activeAggregateCount > 0

  // Filtered rows
  const filteredRows = useMemo(() => {
    const keys = Object.keys(columnFilters).filter(k => hasFilter(k))
    if (keys.length === 0) return rows
    return rows.filter(row => keys.every(k => {
      const f = columnFilters[k]
      if ((f.selected || []).length > 0) return f.selected.includes(row[k])
      const fv = (f.val || '').trim()
      if (!fv) return true
      const raw = row[k]
      const rawNum = parseFloat(String(raw).replace(',', '.'))
      const fNum = parseFloat(fv)
      const val = String(raw ?? '').toLowerCase()
      switch (f.op) {
        case 'eq': return val === fv.toLowerCase()
        case 'contains': return val.includes(fv.toLowerCase())
        case 'gt': return !isNaN(fNum) && !isNaN(rawNum) && rawNum > fNum
        case 'lt': return !isNaN(fNum) && !isNaN(rawNum) && rawNum < fNum
        case 'gte': return !isNaN(fNum) && !isNaN(rawNum) && rawNum >= fNum
        case 'lte': return !isNaN(fNum) && !isNaN(rawNum) && rawNum <= fNum
        case 'between': {
          const fv2 = f.val2?.trim(); const fNum2 = parseFloat(fv2)
          if (isNaN(rawNum) || isNaN(fNum)) return false
          if (!fv2 || isNaN(fNum2)) return rawNum >= fNum
          return rawNum >= fNum && rawNum <= fNum2
        }
        default: return val.includes(fv.toLowerCase())
      }
    }))
  }, [rows, columnFilters])

  // Sorted rows
  const sortedRows = useMemo(() => {
    if (!sortKey) return filteredRows
    return [...filteredRows].sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey]
      const n = v => parseFloat(String(v).replace(',', '.'))
      const r = isNaN(n(av)) ? String(av ?? '').localeCompare(String(bv ?? '')) : n(av) - n(bv)
      return sortDir === 'asc' ? r : -r
    })
  }, [filteredRows, sortKey, sortDir])

  // Compute aggregate for a column
  const computeAggregate = (key, type) => {
    const vals = sortedRows.map(r => parseFloat(String(r[key]).replace(',', '.'))).filter(n => !isNaN(n))
    if (!vals.length) return null
    if (type === 'sum') return vals.reduce((a, b) => a + b, 0)
    if (type === 'avg') return vals.reduce((a, b) => a + b, 0) / vals.length
    if (type === 'max') return Math.max(...vals)
    if (type === 'min') return Math.min(...vals)
    return null
  }

  const aggLabel = (type) => ({ sum: 'Σ', avg: 'x̄', max: '↑', min: '↓' }[type] || '')

  // Numeric detection
  const isNumeric = (key) => {
    const col = localColumns.find(c => c.key === key)
    if (col?.numeric) return true
    if (key.includes('costo') || key.includes('valor') || key.includes('impacto') ||
        key.includes('cantidad') || key.includes('precio')) return true
    const sample = rows.slice(0, 5)
    if (!sample.length) return false
    return sample.every(r => {
      const v = r[key]
      if (v === null || v === undefined || v === '') return true
      const s = String(v).trim()
      return s !== '' && !isNaN(Number(s))
    })
  }

  // Format cell
  const fmtNum = (n) => {
    if (n === null || n === undefined || isNaN(n)) return '—'
    let decimals = 0
    const abs = Math.abs(n)
    if (abs - Math.floor(abs) > 0.0005) {
      const s = n.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')
      decimals = s.split('.')[1]?.length || 0
      if (decimals > 3) decimals = 3
    }
    return n.toLocaleString('de-DE', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })
  }

  const formatCell = (val, key) => {
    if (val === null || val === undefined) return '—'
    if (key.includes('_pct')) {
      const n = parseFloat(val); if (isNaN(n)) return val
      return fmtNum(n * 100) + '%'
    }
    if (key.includes('costo') || key.includes('valor') || key.includes('impacto') || key.includes('precio')) {
      const n = parseFloat(String(val).replace(',', '.'))
      if (!isNaN(n)) return '$' + fmtNum(n)
    }
    if (isNumeric(key)) {
      const n = parseFloat(String(val).replace(',', '.'))
      if (!isNaN(n)) return fmtNum(n)
    }
    return val
  }

  // Export
  const doExport = async (format) => {
    setShowExport(false)
    const cols = visibleColumns
    const data = sortedRows
    const name = title || 'export'

    if (format === 'csv') {
      const header = cols.map(c => `"${c.label}"`).join(',')
      const body = data.map(r => cols.map(c => `"${r[c.key] ?? ''}"`).join(',')).join('\n')
      const blob = new Blob(['﻿' + header + '\n' + body], { type: 'text/csv;charset=utf-8' })
      triggerDownload(blob, `${name}.csv`); return
    }
    if (format === 'xlsx') {
      const XLSX = await import('xlsx')
      const ws = XLSX.utils.aoa_to_sheet([
        cols.map(c => c.label),
        ...data.map(r => cols.map(c => r[c.key] ?? '')),
      ])
      const wb = XLSX.utils.book_new()
      XLSX.utils.book_append_sheet(wb, ws, 'Datos')
      XLSX.writeFile(wb, `${name}.xlsx`); return
    }
    if (format === 'pdf') {
      // PDF simple via window.print de la tabla actual
      alert('Para PDF usa "Imprimir" del navegador (Ctrl+P) o exporta a Excel y convierte.')
    }
  }

  const triggerDownload = (blob, filename) => {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = filename; a.click()
    URL.revokeObjectURL(url)
  }

  const clearColumn = (key) => {
    setColumnFilters(prev => { const c = { ...prev }; delete c[key]; return c })
    setColumnAggregates(prev => { const c = { ...prev }; delete c[key]; return c })
    if (sortKey === key) setSortKey('')
    setColPopup(null)
  }

  const showAll = () => setLocalColumns(cols => cols.map(c => ({ ...c, visible: true })))
  const hideAll = () => setLocalColumns(cols => cols.map(c => ({ ...c, visible: false })))
  const toggleColVisible = (key) => setLocalColumns(cols => cols.map(c => c.key === key ? { ...c, visible: c.visible === false } : c))

  return (
    <div className="flex flex-col rounded-lg border bg-card overflow-visible relative">
      {/* TOOLBAR */}
      <div ref={toolbarRef} className="flex items-center justify-between h-11 px-3.5 border-b bg-secondary/20">
        <div className="flex items-center gap-2">
          {title && <span className="text-sm font-semibold">{title}</span>}
          {!loading && <span className="text-xs font-medium text-muted-foreground bg-muted px-1.5 py-0.5 rounded-full">{filteredRows.length}</span>}
          {activeFilterCount > 0 && (
            <button
              onClick={clearAllFilters}
              className="inline-flex items-center gap-1 text-xs font-medium text-primary bg-primary/10 border border-primary/25 rounded-full px-2 py-0.5 cursor-pointer hover:bg-primary/20"
              title="Limpiar filtros"
            >
              <Filter className="h-2.5 w-2.5" />
              {activeFilterCount}
              <X className="h-2.5 w-2.5" />
            </button>
          )}
          {activeAggregateCount > 0 && (
            <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-400 bg-emerald-500/10 border border-emerald-500/25 rounded-full px-2 py-0.5">
              Σ {activeAggregateCount}
            </span>
          )}
        </div>

        <div className="flex items-center gap-1 relative">
          {/* Campos */}
          <div className="relative">
            <button
              onClick={(e) => { e.stopPropagation(); setShowFields(v => !v); setShowExport(false) }}
              className="inline-flex items-center gap-1.5 h-7 px-2.5 rounded-md border border-border bg-transparent text-xs font-medium text-muted-foreground hover:bg-accent hover:text-foreground cursor-pointer"
            >
              <SlidersHorizontal className="h-3.5 w-3.5" /> Campos
            </button>
            {showFields && (
              <div onClick={e => e.stopPropagation()} className="absolute right-0 top-full mt-1.5 z-50 bg-card border border-border rounded-lg shadow-xl min-w-[280px] py-2">
                <div className="px-3.5 pt-1 pb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Propiedades visibles</div>
                <div className="flex flex-wrap gap-1.5 px-3 pb-2">
                  {localColumns.map(col => (
                    <button
                      key={col.key}
                      onClick={() => toggleColVisible(col.key)}
                      className={cn(
                        "h-6 px-2.5 rounded-full border text-xs transition-colors cursor-pointer",
                        col.visible !== false
                          ? "bg-primary/10 border-primary/30 text-primary font-medium"
                          : "border-border text-muted-foreground hover:text-foreground"
                      )}
                    >{col.label}</button>
                  ))}
                </div>
                <div className="border-t border-border pt-1.5 px-2 flex gap-1">
                  <button onClick={showAll} className="h-6 px-2 rounded text-xs text-muted-foreground hover:bg-accent hover:text-foreground cursor-pointer">Mostrar todos</button>
                  <button onClick={hideAll} className="h-6 px-2 rounded text-xs text-muted-foreground hover:bg-accent hover:text-foreground cursor-pointer">Ocultar todos</button>
                </div>
              </div>
            )}
          </div>

          {/* Exportar */}
          <div className="relative">
            <button
              onClick={(e) => { e.stopPropagation(); setShowExport(v => !v); setShowFields(false) }}
              className="inline-flex items-center gap-1.5 h-7 px-2.5 rounded-md border border-border bg-transparent text-xs font-medium text-muted-foreground hover:bg-accent hover:text-foreground cursor-pointer"
            >
              <Download className="h-3.5 w-3.5" /> Exportar
            </button>
            {showExport && (
              <div onClick={e => e.stopPropagation()} className="absolute right-0 top-full mt-1.5 z-50 bg-card border border-border rounded-lg shadow-xl min-w-[220px] py-2">
                <div className="px-3.5 pt-1 pb-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Exportar como</div>
                <div className="px-1.5 pb-1 flex flex-col gap-0.5">
                  <ExportRow icon={FileText} label="CSV" desc="Separado por comas" onClick={() => doExport('csv')} />
                  <ExportRow icon={TableIcon} label="Excel" desc="Archivo .xlsx" onClick={() => doExport('xlsx')} />
                  <ExportRow icon={FileIcon} label="PDF" desc="Documento PDF" onClick={() => doExport('pdf')} />
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* TABLA */}
      <div className="overflow-auto max-h-[calc(100vh-260px)]">
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr>
              {visibleColumns.map(col => (
                <th
                  key={col.key}
                  onClick={(e) => openColPopup(col.key, e)}
                  className={cn(
                    "text-left px-3 h-9 text-[11px] font-semibold uppercase tracking-wider bg-background border-b border-border cursor-pointer select-none whitespace-nowrap sticky top-0 z-10 transition-colors",
                    hasFilter(col.key) ? "text-primary" : "text-muted-foreground",
                    sortKey === col.key && "text-foreground",
                    columnAggregates[col.key] && "border-b-emerald-500",
                    colPopup === col.key && "bg-primary/10 text-primary",
                    "hover:text-foreground"
                  )}
                >
                  <div className="flex items-center gap-1">
                    <span className="flex-1">{col.label}</span>
                    {sortKey === col.key && (
                      sortDir === 'asc' ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />
                    )}
                    {hasFilter(col.key) && <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0" />}
                  </div>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              [...Array(8)].map((_, i) => (
                <tr key={i}><td colSpan={visibleColumns.length} className="p-3"><div className="h-3.5 rounded bg-muted/50 animate-pulse" /></td></tr>
              ))
            ) : (
              <>
                {hasAggregates && sortedRows.length > 0 && (
                  <tr className="bg-emerald-500/5 sticky z-[5]" style={{ top: '36px' }}>
                    {visibleColumns.map(col => (
                      <td key={col.key} className="px-3 py-2 font-semibold border-b-2 border-emerald-500/25 bg-emerald-500/5">
                        {columnAggregates[col.key] && (
                          <>
                            <span className="text-[10px] text-emerald-400 font-bold mr-1">{aggLabel(columnAggregates[col.key])}</span>
                            <span className="text-sm">{formatCell(computeAggregate(col.key, columnAggregates[col.key]), col.key)}</span>
                          </>
                        )}
                      </td>
                    ))}
                  </tr>
                )}
                {sortedRows.length === 0 ? (
                  <tr><td colSpan={visibleColumns.length} className="py-12 text-center">
                    <div className="flex flex-col items-center gap-2 text-muted-foreground text-sm">
                      <Inbox className="h-6 w-6" /> Sin resultados
                    </div>
                  </td></tr>
                ) : sortedRows.map((row, idx) => (
                  <tr
                    key={row.id ?? idx}
                    onClick={() => onRowClick?.(row)}
                    className={cn("border-b border-border/40 hover:bg-accent/30 transition-colors group", onRowClick && "cursor-pointer")}
                  >
                    {visibleColumns.map(col => {
                      const value = row[col.key]
                      const custom = renderCell?.(row, col, value)
                      return (
                        <td key={col.key} className={cn("px-3 py-2 align-middle", col.nowrap && "whitespace-nowrap")}>
                          {custom !== undefined && custom !== null ? custom : formatCell(value, col.key)}
                        </td>
                      )
                    })}
                  </tr>
                ))}
              </>
            )}
          </tbody>
        </table>
      </div>

      {/* FOOTER */}
      {!loading && sortedRows.length > 0 && (
        <div className="px-3.5 py-2 text-xs text-muted-foreground border-t">
          {sortedRows.length} filas
          {activeFilterCount > 0 && <span> · {rows.length - sortedRows.length} filtradas</span>}
        </div>
      )}

      {/* COL POPUP */}
      {colPopup && createPortal(
        <div className="fixed inset-0 z-[9999]" onClick={() => setColPopup(null)}>
          <div
            className="fixed min-w-[220px] max-w-[300px] bg-card border border-border rounded-lg shadow-2xl py-2"
            style={colPopupStyle}
            onClick={e => e.stopPropagation()}
          >
            {/* Filtrar */}
            <div className="px-3 py-1">
              <label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground block mb-1.5">Filtrar</label>
              {getColumnOptions(colPopup).length > 0 ? (
                <div className="flex flex-col gap-0.5 max-h-56 overflow-y-auto py-1">
                  {getColumnOptions(colPopup).map(opt => (
                    <label key={opt.value} className="flex items-center gap-2 px-1 py-1 rounded text-xs cursor-pointer hover:bg-accent">
                      <input
                        type="checkbox"
                        checked={isOptionSelected(colPopup, opt.value)}
                        onChange={() => toggleOption(colPopup, opt.value)}
                        className="cursor-pointer accent-primary"
                      />
                      {opt.color && <span className="w-2 h-2 rounded-full" style={{ background: opt.color }} />}
                      {opt.label}
                    </label>
                  ))}
                </div>
              ) : (
                <>
                  <select
                    value={getFilterOp(colPopup)}
                    onChange={e => setFilter(colPopup, { op: e.target.value })}
                    className="w-full h-7 rounded border border-border bg-input text-xs px-2 mb-1.5 cursor-pointer"
                  >
                    {Object.entries(OP_LABELS).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
                  </select>
                  <div className="flex flex-col gap-1">
                    <input
                      ref={inputRef}
                      value={getFilterVal(colPopup)}
                      onChange={e => setFilter(colPopup, { val: e.target.value })}
                      onKeyDown={e => { if (e.key === 'Enter' || e.key === 'Escape') setColPopup(null) }}
                      placeholder={getFilterOp(colPopup) === 'between' ? 'Desde' : 'Valor'}
                      className="w-full h-7 rounded border border-border bg-input text-xs px-2 outline-none focus:border-primary"
                    />
                    {getFilterOp(colPopup) === 'between' && (
                      <input
                        value={getFilterVal2(colPopup)}
                        onChange={e => setFilter(colPopup, { val2: e.target.value })}
                        placeholder="Hasta"
                        className="w-full h-7 rounded border border-border bg-input text-xs px-2 outline-none focus:border-primary"
                      />
                    )}
                  </div>
                </>
              )}
            </div>

            {/* Ordenar */}
            <div className="px-3 py-1">
              <label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground block mb-1.5">Ordenar</label>
              <div className="flex gap-1">
                <SortBtn active={sortKey === colPopup && sortDir === 'asc'} onClick={() => setSort(colPopup, 'asc')}>
                  <ChevronUp className="h-3 w-3" /> Ascendente
                </SortBtn>
                <SortBtn active={sortKey === colPopup && sortDir === 'desc'} onClick={() => setSort(colPopup, 'desc')}>
                  <ChevronDown className="h-3 w-3" /> Descendente
                </SortBtn>
              </div>
            </div>

            {/* Subtotal */}
            {isNumeric(colPopup) && (
              <>
                <div className="h-px bg-border my-1" />
                <div className="px-3 py-1">
                  <label className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground block mb-1.5">Subtotal</label>
                  <div className="flex gap-1 flex-wrap">
                    {AGG_OPTIONS.map(agg => (
                      <button
                        key={agg.value}
                        onClick={() => toggleAggregate(colPopup, agg.value)}
                        className={cn(
                          "inline-flex items-center gap-1 h-6 px-2 rounded text-xs transition-colors cursor-pointer",
                          columnAggregates[colPopup] === agg.value
                            ? "bg-emerald-500/10 border border-emerald-500/30 text-emerald-400"
                            : "border border-border text-muted-foreground hover:text-foreground"
                        )}
                      >
                        <span>{agg.icon}</span> {agg.label}
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}

            {(hasFilter(colPopup) || columnAggregates[colPopup] || sortKey === colPopup) && (
              <div className="border-t border-border pt-1.5 px-2 mt-1">
                <button
                  onClick={() => clearColumn(colPopup)}
                  className="w-full h-7 rounded text-xs text-destructive hover:bg-destructive/10 cursor-pointer"
                >
                  Limpiar todo
                </button>
              </div>
            )}
          </div>
        </div>,
        document.body
      )}
    </div>
  )
}

function ExportRow({ icon: Icon, label, desc, onClick }) {
  return (
    <button onClick={onClick} className="flex items-center gap-2.5 px-2.5 py-2 rounded hover:bg-accent cursor-pointer w-full text-left">
      <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
      <span className="text-sm text-foreground font-medium flex-1">{label}</span>
      <span className="text-[11px] text-muted-foreground whitespace-nowrap">{desc}</span>
    </button>
  )
}

function SortBtn({ active, onClick, children }) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "flex-1 inline-flex items-center gap-1 h-7 px-2 rounded text-xs justify-center transition-colors cursor-pointer",
        active
          ? "bg-primary/10 border border-primary/30 text-primary"
          : "border border-border text-muted-foreground hover:text-foreground"
      )}
    >{children}</button>
  )
}

// frontend/app/src/components/OsDataTable.vue
<template>
  <div class="os-table-wrapper">

    <!-- ── TOOLBAR ── -->
    <div class="table-toolbar">
      <div class="toolbar-left">
        <span class="table-title">{{ title }}</span>
        <span v-if="!loading" class="row-count">{{ filteredRows.length }}</span>
      </div>
      <div class="toolbar-right">
        <!-- Filtrar -->
        <div class="toolbar-btn-wrap" ref="filterRef">
          <button class="toolbar-btn" :class="{ active: activeFilters.length > 0 }" @click.stop="showFilter = !showFilter">
            <FilterIcon :size="14" />
            <span>Filtrar</span>
            <span v-if="activeFilters.length > 0" class="btn-badge">{{ activeFilters.length }}</span>
          </button>
          <!-- Popup filtros -->
          <div v-if="showFilter" class="popup filter-popup" @click.stop>
            <div class="pp-section-label">Filtros</div>
            <div class="filter-list">
              <div v-for="(f, i) in activeFilters" :key="i" class="filter-row">
                <select v-model="f.field" class="pp-select">
                  <option v-for="col in filterableCols" :key="col.key" :value="col.key">{{ col.label }}</option>
                </select>
                <select v-model="f.op" class="pp-select pp-select-op">
                  <option value="contains">contiene</option>
                  <option value="eq">igual a</option>
                  <option value="gte">≥</option>
                  <option value="lte">≤</option>
                </select>
                <input v-model="f.value" class="pp-input" placeholder="valor" @keyup.enter="showFilter = false" />
                <button class="pp-icon-btn" @click="removeFilter(i)"><XIcon :size="12" /></button>
              </div>
              <div v-if="activeFilters.length === 0" class="pp-empty">Sin filtros activos</div>
            </div>
            <div class="pp-footer">
              <button class="pp-action-btn" @click="addFilter"><PlusIcon :size="13" />Añadir filtro</button>
              <button v-if="activeFilters.length > 0" class="pp-action-btn danger" @click="activeFilters = []">Limpiar todo</button>
            </div>
          </div>
        </div>

        <!-- Campos (Display) -->
        <div class="toolbar-btn-wrap" ref="fieldsRef">
          <button class="toolbar-btn" @click.stop="showFields = !showFields">
            <SlidersHorizontalIcon :size="14" />
            <span>Campos</span>
          </button>
          <!-- Popup campos -->
          <div v-if="showFields" class="popup fields-popup" @click.stop>
            <div class="pp-section-label">Propiedades visibles</div>
            <div class="fields-pills">
              <button
                v-for="col in localColumns"
                :key="col.key"
                class="field-pill"
                :class="{ active: col.visible }"
                @click="col.visible = !col.visible"
              >{{ col.label }}</button>
            </div>
            <div class="pp-divider" />
            <div class="pp-footer">
              <button class="pp-action-btn" @click="showAll">Mostrar todos</button>
              <button class="pp-action-btn" @click="hideAll">Ocultar todos</button>
            </div>
          </div>
        </div>

        <!-- Exportar -->
        <div class="toolbar-btn-wrap" ref="exportRef">
          <button class="toolbar-btn" @click.stop="showExport = !showExport">
            <DownloadIcon :size="14" />
            <span>Exportar</span>
          </button>
          <!-- Popup export -->
          <div v-if="showExport" class="popup export-popup" @click.stop>
            <div class="pp-section-label">Exportar como</div>
            <div class="export-list">
              <button class="export-row" @click="doExport('csv')">
                <FileTextIcon :size="15" class="export-icon" />
                <span class="export-label">CSV</span>
                <span class="export-desc">Separado por comas</span>
              </button>
              <button class="export-row" @click="doExport('xlsx')">
                <TableIcon :size="15" class="export-icon" />
                <span class="export-label">Excel</span>
                <span class="export-desc">Archivo .xlsx</span>
              </button>
              <button class="export-row" @click="doExport('pdf')">
                <FileIcon :size="15" class="export-icon" />
                <span class="export-label">PDF</span>
                <span class="export-desc">Documento PDF</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- ── TABLA ── -->
    <div class="table-scroll">
      <table class="os-table">
        <thead>
          <tr>
            <th v-for="col in visibleColumns" :key="col.key" @click="setSort(col.key)" class="th">
              <div class="th-inner">
                {{ col.label }}
                <span v-if="sortKey === col.key" class="sort-icon">
                  <component :is="sortDir === 'asc' ? ChevronUpIcon : ChevronDownIcon" :size="12" />
                </span>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          <!-- Skeleton loading -->
          <template v-if="loading">
            <tr v-for="n in 8" :key="n" class="skeleton-row">
              <td v-for="col in visibleColumns" :key="col.key">
                <div class="skeleton-cell" />
              </td>
            </tr>
          </template>
          <!-- Datos -->
          <template v-else>
            <tr
              v-for="(row, idx) in sortedRows"
              :key="row._pk || row.mes || row._key || idx"
              class="data-row"
              :class="{ selected: isSelected(row) }"
              @click="selectRow(row)"
              @dblclick="emit('row-dblclick', row)"
            >
              <td v-for="col in visibleColumns" :key="col.key" class="td">
                <span class="cell-value">{{ formatCell(row[col.key], col.key) }}</span>
              </td>
            </tr>
            <!-- Vacío -->
            <tr v-if="sortedRows.length === 0">
              <td :colspan="visibleColumns.length" class="empty-cell">
                <div class="empty-state">
                  <InboxIcon :size="24" />
                  <span>Sin resultados</span>
                </div>
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>

    <!-- ── PIE: total filas ── -->
    <div v-if="!loading && sortedRows.length > 0" class="table-footer">
      {{ sortedRows.length }} filas
      <span v-if="activeFilters.length > 0"> · {{ rows.length - sortedRows.length }} filtradas</span>
    </div>

  </div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import {
  FilterIcon, SlidersHorizontalIcon, DownloadIcon, XIcon, PlusIcon,
  ChevronUpIcon, ChevronDownIcon, FileTextIcon, TableIcon, FileIcon, InboxIcon
} from 'lucide-vue-next'

const props = defineProps({
  rows:    { type: Array,   default: () => [] },
  columns: { type: Array,   default: () => [] },
  loading: { type: Boolean, default: false },
  title:   { type: String,  default: '' },
  recurso: { type: String,  default: '' },
  mes:     { type: String,  default: '' },
})

const emit = defineEmits(['row-click', 'row-dblclick'])

// ── Columnas locales (copia para mutar visible) ──────
const localColumns = ref([])
watch(() => props.columns, (cols) => {
  localColumns.value = cols.map(c => ({ ...c }))
}, { immediate: true })

const visibleColumns  = computed(() => localColumns.value.filter(c => c.visible))
const filterableCols  = computed(() => localColumns.value)

// ── Filtros ──────────────────────────────────────────
const showFilter    = ref(false)
const showFields    = ref(false)
const showExport    = ref(false)
const activeFilters = ref([])

function addFilter() {
  activeFilters.value.push({ field: localColumns.value[0]?.key || '', op: 'contains', value: '' })
}
function removeFilter(i) { activeFilters.value.splice(i, 1) }

const filteredRows = computed(() => {
  if (activeFilters.value.length === 0) return props.rows
  return props.rows.filter(row => {
    return activeFilters.value.every(f => {
      const val = String(row[f.field] ?? '').toLowerCase()
      const fv  = String(f.value).toLowerCase()
      if (f.op === 'contains') return val.includes(fv)
      if (f.op === 'eq')       return val === fv
      if (f.op === 'gte')      return parseFloat(row[f.field]) >= parseFloat(f.value)
      if (f.op === 'lte')      return parseFloat(row[f.field]) <= parseFloat(f.value)
      return true
    })
  })
})

// ── Ordenamiento ─────────────────────────────────────
const sortKey = ref('')
const sortDir = ref('asc')
function setSort(key) {
  if (sortKey.value === key) sortDir.value = sortDir.value === 'asc' ? 'desc' : 'asc'
  else { sortKey.value = key; sortDir.value = 'asc' }
}
const sortedRows = computed(() => {
  if (!sortKey.value) return filteredRows.value
  return [...filteredRows.value].sort((a, b) => {
    const av = a[sortKey.value], bv = b[sortKey.value]
    const n = (v) => parseFloat(String(v).replace(',', '.'))
    const r = isNaN(n(av)) ? String(av).localeCompare(String(bv)) : n(av) - n(bv)
    return sortDir.value === 'asc' ? r : -r
  })
})

// ── Selección de fila ─────────────────────────────────
const selectedRow = ref(null)
function selectRow(row) {
  selectedRow.value = row
  emit('row-click', row)
}
function isSelected(row) {
  if (!selectedRow.value) return false
  const s = selectedRow.value
  if (s._pk   != null) return row._pk   === s._pk
  if (s._key  != null) return row._key  === s._key
  if (s.mes   != null) return row.mes   === s.mes
  return false
}

// ── Campos ───────────────────────────────────────────
function showAll() { localColumns.value.forEach(c => c.visible = true) }
function hideAll() { localColumns.value.forEach(c => c.visible = false) }

// ── Exportar ─────────────────────────────────────────
function doExport(format) {
  showExport.value = false
  const visibleKeys = visibleColumns.value.map(c => c.key)
  const filters = activeFilters.value.length > 0 ? JSON.stringify(activeFilters.value) : undefined
  const params = new URLSearchParams({ format, fields: JSON.stringify(visibleKeys) })
  if (props.mes) params.set('mes', props.mes)
  if (filters)   params.set('filters', filters)
  window.open(`/api/export/${props.recurso}?${params}`, '_blank')
}

// ── Formato de celda ─────────────────────────────────
function formatCell(val, key) {
  if (val === null || val === undefined) return '—'
  // Porcentajes
  if (key.includes('_pct') || key.includes('_margen')) {
    const n = parseFloat(val)
    return isNaN(n) ? val : (n * 100).toFixed(1) + '%'
  }
  // Moneda
  if (key.startsWith('fin_') || key.startsWith('cto_') || key.startsWith('car_') || key.includes('ventas') || key.includes('ticket') || key.includes('costo') || key.includes('utilidad')) {
    const n = parseFloat(String(val).replace(',', '.'))
    if (!isNaN(n)) return '$' + n.toLocaleString('es-CO', { maximumFractionDigits: 0 })
  }
  return val
}

// ── Cerrar popups al hacer clic fuera ────────────────
function handleOutsideClick() {
  showFilter.value = false
  showFields.value = false
  showExport.value = false
}
onMounted(() => document.addEventListener('click', handleOutsideClick))
onUnmounted(() => document.removeEventListener('click', handleOutsideClick))
</script>

<style scoped>
/* ── WRAPPER ── */
.os-table-wrapper {
  background: var(--bg-card);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-lg);
  overflow: hidden;
}

/* ── TOOLBAR ── */
.table-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 44px;
  padding: 0 14px;
  border-bottom: 1px solid var(--border-default);
  background: var(--bg-toolbar);
}
.toolbar-left { display: flex; align-items: center; gap: 8px; }
.table-title  { font-size: 13px; font-weight: 600; color: var(--text-primary); }
.row-count    {
  font-size: 11px; font-weight: 500;
  color: var(--text-tertiary);
  background: rgba(0,0,0,0.06);
  padding: 1px 7px; border-radius: var(--radius-full);
}
.toolbar-right { display: flex; align-items: center; gap: 4px; }

/* ── TOOLBAR BUTTONS ── */
.toolbar-btn-wrap { position: relative; }
.toolbar-btn {
  display: inline-flex; align-items: center; gap: 5px;
  height: 28px; padding: 0 10px;
  border-radius: var(--radius-md);
  border: 1px solid var(--border-default);
  background: transparent;
  font-size: 12px; font-weight: 500;
  color: var(--text-secondary);
  cursor: pointer;
  transition: background 80ms, color 80ms, border-color 80ms;
  white-space: nowrap;
  font-family: var(--font-sans);
}
.toolbar-btn:hover { background: var(--bg-card-hover); color: var(--text-primary); border-color: var(--border-strong); }
.toolbar-btn.active { color: var(--accent); border-color: var(--accent-border); background: var(--accent-muted); }
.btn-badge {
  background: var(--accent); color: white;
  font-size: 10px; font-weight: 700;
  padding: 0 5px; border-radius: var(--radius-full);
  min-width: 16px; text-align: center;
}

/* ── POPUPS — base ── */
.popup {
  position: absolute; top: calc(100% + 6px); right: 0;
  background: var(--bg-modal);
  border: 1px solid var(--border-strong);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-lg);
  z-index: 200;
  min-width: 240px;
  animation: popup-in 120ms ease-out;
  overflow: hidden;
}
@keyframes popup-in {
  from { opacity: 0; transform: translateY(-4px) scale(0.98); }
  to   { opacity: 1; transform: translateY(0)    scale(1); }
}

/* Label de sección (encabezado sin botón X, como Linear) */
.pp-section-label {
  padding: 10px 14px 6px;
  font-size: 11px; font-weight: 600;
  text-transform: uppercase; letter-spacing: 0.07em;
  color: var(--text-tertiary);
}

/* Divider interno */
.pp-divider { height: 1px; background: var(--border-subtle); margin: 4px 0; }

/* Footer */
.pp-footer {
  display: flex; align-items: center; gap: 4px;
  padding: 6px 10px 10px;
  border-top: 1px solid var(--border-subtle);
}
.pp-action-btn {
  display: inline-flex; align-items: center; gap: 4px;
  height: 26px; padding: 0 8px; border-radius: var(--radius-sm);
  border: none; background: transparent;
  font-size: 12px; color: var(--text-secondary); cursor: pointer;
  transition: background 60ms; font-family: var(--font-sans);
}
.pp-action-btn:hover { background: var(--bg-card-hover); color: var(--text-primary); }
.pp-action-btn.danger:hover { color: var(--color-error); }

/* Vacío */
.pp-empty { padding: 10px 14px; font-size: 12px; color: var(--text-tertiary); }

/* Ícono btn dentro de popup */
.pp-icon-btn {
  width: 22px; height: 22px; border-radius: var(--radius-sm); border: none;
  background: transparent; color: var(--text-tertiary); cursor: pointer;
  display: flex; align-items: center; justify-content: center;
  flex-shrink: 0; transition: background 60ms;
}
.pp-icon-btn:hover { background: var(--bg-card-hover); color: var(--color-error); }

/* ── FILTRAR ── */
.filter-popup { min-width: 440px; }
.filter-list  { padding: 2px 10px 6px; display: flex; flex-direction: column; gap: 5px; max-height: 220px; overflow-y: auto; }
.filter-row   { display: flex; align-items: center; gap: 5px; }
.pp-select {
  height: 27px; border-radius: var(--radius-sm);
  border: 1px solid var(--border-default);
  background: var(--bg-input);
  font-size: 12px; color: var(--text-primary);
  padding: 0 7px; outline: none;
  font-family: var(--font-sans); cursor: pointer;
}
.pp-select:focus { border-color: var(--accent); }
.pp-select        { min-width: 130px; }
.pp-select-op     { min-width: 80px; }
.pp-input {
  flex: 1; height: 27px; border-radius: var(--radius-sm);
  border: 1px solid var(--border-default);
  background: var(--bg-input);
  font-size: 12px; color: var(--text-primary);
  padding: 0 8px; outline: none;
  font-family: var(--font-sans);
}
.pp-input:focus { border-color: var(--accent); }

/* ── CAMPOS — pills ── */
.fields-popup { min-width: 280px; }
.fields-pills {
  display: flex; flex-wrap: wrap; gap: 6px;
  padding: 6px 12px 10px;
  max-height: 220px; overflow-y: auto;
}
.field-pill {
  display: inline-flex; align-items: center;
  height: 26px; padding: 0 10px;
  border-radius: var(--radius-full);
  border: 1px solid var(--border-default);
  background: transparent;
  font-size: 12px; color: var(--text-secondary);
  cursor: pointer; transition: all 80ms;
  font-family: var(--font-sans);
}
.field-pill:hover { border-color: var(--border-strong); color: var(--text-primary); }
.field-pill.active {
  background: var(--accent-muted);
  border-color: var(--accent-border);
  color: var(--accent);
  font-weight: 500;
}

/* ── EXPORTAR ── */
.export-popup { min-width: 220px; }
.export-list  { padding: 4px 6px 8px; display: flex; flex-direction: column; gap: 1px; }
.export-row {
  display: flex; align-items: center; gap: 10px;
  padding: 8px 10px; border-radius: var(--radius-md);
  border: none; background: transparent; width: 100%;
  cursor: pointer; transition: background 80ms;
  font-family: var(--font-sans);
}
.export-row:hover { background: var(--bg-card-hover); }
.export-icon { color: var(--text-tertiary); flex-shrink: 0; }
.export-label { font-size: 13px; color: var(--text-primary); font-weight: 500; flex: 1; text-align: left; }
.export-desc  { font-size: 11px; color: var(--text-tertiary); white-space: nowrap; }

/* ── TABLA ── */
.table-scroll { overflow-x: auto; }
.os-table     { width: 100%; border-collapse: collapse; font-size: 13px; }

.th {
  text-align: left; padding: 0 12px;
  height: 36px;
  font-size: 11px; font-weight: 600;
  color: var(--text-tertiary);
  background: var(--bg-app);
  border-bottom: 1px solid var(--border-default);
  white-space: nowrap; cursor: pointer; user-select: none;
  position: sticky; top: 0; z-index: 5;
}
.th:hover { color: var(--text-secondary); }
.th-inner { display: flex; align-items: center; gap: 4px; }

.data-row { cursor: pointer; transition: background 60ms; }
.data-row:hover    { background: var(--bg-row-hover); }
.data-row.selected { background: var(--bg-row-selected); }

.td {
  padding: 0 12px;
  height: 36px;
  border-bottom: 1px solid var(--border-subtle);
  color: var(--text-primary);
  white-space: nowrap;
  max-width: 240px; overflow: hidden; text-overflow: ellipsis;
}
.cell-value { font-size: 13px; }

/* skeleton */
.skeleton-row td { padding: 8px 12px; border-bottom: 1px solid var(--border-subtle); }
.skeleton-cell { height: 14px; border-radius: var(--radius-sm); background: linear-gradient(90deg, rgba(0,0,0,0.05) 25%, rgba(0,0,0,0.09) 50%, rgba(0,0,0,0.05) 75%); background-size: 200% 100%; animation: shimmer 1.4s infinite; }
@keyframes shimmer { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }

/* vacío */
.empty-cell { padding: 48px 16px; text-align: center; }
.empty-state { display: flex; flex-direction: column; align-items: center; gap: 8px; color: var(--text-tertiary); font-size: 13px; }

/* footer */
.table-footer { padding: 8px 14px; font-size: 12px; color: var(--text-tertiary); border-top: 1px solid var(--border-subtle); }

/* botones helper */
.icon-btn {
  width: 24px; height: 24px; border-radius: var(--radius-sm); border: none;
  background: transparent; color: var(--text-tertiary); cursor: pointer;
  display: flex; align-items: center; justify-content: center; transition: background 60ms;
}
.icon-btn:hover { background: var(--bg-card-hover); color: var(--text-primary); }
.icon-btn.danger:hover { background: var(--color-error-bg); color: var(--color-error); }
.btn-ghost-sm {
  display: inline-flex; align-items: center; gap: 4px;
  height: 26px; padding: 0 8px; border-radius: var(--radius-sm);
  border: none; background: transparent;
  font-size: 12px; color: var(--text-secondary); cursor: pointer;
  transition: background 60ms; font-family: var(--font-sans);
}
.btn-ghost-sm:hover { background: var(--bg-card-hover); color: var(--text-primary); }
.btn-ghost-sm.danger:hover { color: var(--color-error); }
</style>
